version: "3.8"
services:
  db:
    env_file:
      - .env
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
volumes:
  db:
    driver: local
